### ISSUE TITLE
can i get an example or details about chunckfiles? (train.csv)

### ISSUE THREAD

**Issue by hehehwang** [NURx2/pycode2vec#3]
Hi 
I'm having little confusion about chunck files that i need to prepare.
can you give me some example or details about chunck files? (.csv)

also, on line 6 at `default.config`, i think 
`#   and data will be extracted from .java files found in those sub-dirs).` sould be
`#   and data will be extracted from .py files found in those sub-dirs).`

Thank you

**Comment by NURx2** [comment]
Hi @hehehwang ,

The `train.csv` and `test.csv` files should contain `code_block` column, where you put any interpretable peace of python 3 code (for example: `import pandas`) in each row. Next you run `train.sh` and the script distributes each row of `code_block` column to files in `input_chunks/train` and `input_chunks/val` directories, naming files according to the corresponding `target` field (which should have a string type).

Thanks for your comment. These instructions are outdated, you shouldn't rename TRAIN_DIR, VAL_DIR or TEST_DIR. Deleted it. Take a look at Readme.md for up-to-date tutorial.

Best,
Ainur

**Comment by hehehwang** [comment]
Thank you for quick and kind explanation!
my questions is, what are `target` field for? just naming?

if so, is this csv file valid?
https://gist.github.com/hehehwang/e1c6bd93df4002f5c1143accf6ec7f41

**Comment by NURx2** [comment]
The `target` field is necessary to train meaningful code vectors, because code2vec project was originally designed to compute method embeddings for predicting method names.

Your csv file is valid, but you should rather use meaningful target names.

**Comment by hehehwang** [comment]
ahh now i understand 
i thought astminer can parse code and put method names (FunctionDef nodes) on target

thank you again for your help and works
have a nice weekend!
